import type {
  BrainstormCard,
  ConsequenceItem,
  EvaluationArgument,
  FacultyAngle,
  Task2Data,
  VocabItem
} from "../types";

export type {
  BrainstormCard,
  ConsequenceItem,
  EvaluationArgument,
  FacultyAngle,
  Task2Data,
  VocabItem
};

export const TASK2_DATA: Task2Data = {
  id: "historical-objects-repatriation-task2",

  taskType: "Opinion Essay: Agree or Disagree",

  title: "Repatriation of Historical Objects to Countries of Origin",

  questionText:
    "Historical objects should be brought back to their country of origin.\n\nDo you agree or disagree with this statement.",

  audioUrl: "materials/historical-objects-repatriation-briefing.m4a",

  timingSeconds: 180,

  sampleIntro:
    "It is often asserted that ancient artifacts and cultural treasures currently held in foreign museums ought to be returned to their countries of origin. I firmly agree with this statement, as historical objects embody the cultural soul of their native civilizations and their repatriation is essential for both moral justice and the economic sovereignty of source nations.",

  sampleConclusion:
    "In conclusion, I wholeheartedly agree that historical treasures should be repatriated to their nations of origin. This step is indispensable not only for restoring cultural dignity and redressing colonial plunder, but also for granting origin societies rightful academic access and vital heritage tourism revenue.",

  vocabList: [
    {
      word: "cultural repatriation",
      meaning: "The formal process of returning cultural artifacts and sacred objects to their legitimate country of origin.",
      example:
        "Developing nations are actively lobbying international tribunals for the cultural repatriation of their ancestral treasures."
    },
    {
      word: "ancestral heritage",
      meaning: "The traditions, monuments, and historical relics inherited from past generations of a specific society.",
      example:
        "Depriving a community of its ancestral heritage creates a painful sense of cultural alienation among younger generations."
    },
    {
      word: "illicitly plundered",
      meaning: "Looted, stolen, or taken by force through military aggression, colonization, or unauthorized excavation.",
      example:
        "Many masterpieces showcased in Western capitals were illicitly plundered during 19th-century imperial expeditions."
    },
    {
      word: "rightful custody",
      meaning: "Lawful and morally legitimate ownership, stewardship, and preservation of historic treasures.",
      example:
        "International law increasingly recognizes that source nations hold rightful custody over their national heritage."
    },
    {
      word: "rectify colonial injustices",
      meaning: "Remedy or make moral amends for historical crimes, exploitation, and theft committed during imperial rule.",
      example:
        "Returning royal artifacts is a tangible step forward to rectify colonial injustices and restore diplomatic trust."
    },
    {
      word: "spiritual and ceremonial significance",
      meaning: "Possessing profound religious, ancestral, or traditional sanctity within indigenous community rituals.",
      example:
        "Sacred totems and royal regalia carry deep spiritual and ceremonial significance that cannot be experienced behind museum glass."
    },
    {
      word: "cultural sovereignty",
      meaning: "The autonomy and right of a nation or indigenous people to curate, manage, and celebrate their own history.",
      example:
        "Demanding the return of antiquity collections is an assertion of cultural sovereignty by post-colonial states."
    },
    {
      word: "deprive native scholars",
      meaning: "Prevent local researchers, historians, and students from accessing their own history due to geographic and financial barriers.",
      example:
        "Housing artifacts overseas deprives native scholars of firsthand academic research opportunities."
    },
    {
      word: "state-of-the-art conservation",
      meaning: "Cutting-edge museum facilities equipped with advanced climate control, digital security, and preservation technology.",
      example:
        "The newly constructed Grand Egyptian Museum features state-of-the-art conservation labs rivaling any European institution."
    },
    {
      word: "heritage tourism revenue",
      meaning: "Economic dividends generated by museum admission, cultural exhibits, and international traveler visits.",
      example:
        "Repatriated antiquities stimulate local economies by channeling heritage tourism revenue directly to origin nations."
    }
  ],

  vocabHunt: [
    "cultural repatriation",
    "ancestral heritage",
    "illicitly plundered",
    "rightful custody",
    "rectify colonial injustices",
    "spiritual and ceremonial significance",
    "cultural sovereignty",
    "heritage tourism revenue"
  ],

  /*
   * BODY 1 — AGREE (Cultural Identity, Sacred Value & Moral Justice)
   */
  /*
   * ================================================================
   * STEP 6: AGREE POINTS — WHY ARTIFACTS SHOULD BE REPATRIATED
   * ================================================================
   * Levelled points for students:
   * Level 1: Core Claim & Cultural Identity (High Impact)
   * Level 2: Economic & Architectural Wholeness (Strategic Depth)
   * Level 3: Academic Equity & Global Human Rights (Advanced)
   * Plus 4 Nuances & Practical Caveats
   */
  consequences: [
    {
      type: "positive",
      level: "Level 1: High Impact (Identity)",
      simpleTakeaway: "Historical relics are sacred symbols of living identity and ancestral worship, not decorative art in foreign display cases.",
      collocation: "living cultural heritage",
      title: "Embodiment of Cultural Identity & Living Traditions",
      desc:
        "Historical relics are not mere decorative museum art; they embody the spiritual soul, living religious consciousness, and collective identity of the civilizations that produced them.",
      example:
        "Sacred Maori ancestral heads returned from European vaults to New Zealand enabled native communities to conduct vital funeral rites and restore tribal dignity."
    },
    {
      type: "positive",
      level: "Level 1: High Impact (Justice)",
      simpleTakeaway: "Most overseas antiquities were seized through violent colonial military raids and imperial extortion, not ethical trade.",
      collocation: "illicit colonial expropriation",
      title: "Moral Restitution for Colonial Looting & Coercion",
      desc:
        "An overwhelming majority of non-Western artifacts residing in metropolitan museums were acquired through violent military invasions, punitive expeditions, or colonial extortion rather than lawful trade.",
      example:
        "During the 1897 British punitive expedition against the Kingdom of Benin, thousands of sacred royal bronzes were systematically looted from royal palaces and auctioned."
    },
    {
      type: "positive",
      level: "Level 2: Strategic Depth (Economy)",
      simpleTakeaway: "Origin countries are unfairly denied the vast tourism and hospitality revenues generated by their own cultural heritage.",
      collocation: "economic sovereignty",
      title: "Economic Sovereignty & Heritage Tourism Dividends",
      desc:
        "Western institutions profit immensely from ticket admissions, merchandise, and hotel bookings drawn by foreign antiquities, while source nations remain economically disadvantaged.",
      example:
        "Greece could substantially expand its cultural economy if the Parthenon Marbles were displayed in Athens rather than driving commercial footfall in London."
    },
    {
      type: "positive",
      level: "Level 2: Strategic Depth (Context)",
      simpleTakeaway: "Sculptures and temple friezes lose their narrative story when ripped out of their original architectural setting.",
      collocation: "contextual integrity",
      title: "Architectural & Contextual Narrative Wholeness",
      desc:
        "Ancient monuments were conceived as continuous artistic narratives; severing friezes and statues across foreign continents diminishes their educational and aesthetic value.",
      example:
        "The Parthenon frieze can only be fully comprehended when viewed in direct sight of the Acropolis temple under natural Mediterranean light."
    },
    {
      type: "positive",
      level: "Level 3: Global Dimension (Equity)",
      simpleTakeaway: "Native students and researchers face visa denials and prohibitive flight costs to study their own ancestors' creations.",
      collocation: "equitable scholarly access",
      title: "Academic Access for Native Scholars & Students",
      desc:
        "Holding primary historical sources in foreign capitals severely disadvantages local researchers and archaeologists from source nations due to visa restrictions and prohibitive costs.",
      example:
        "African historians frequently struggle to obtain European visas to access pre-colonial manuscripts and artifacts stored in European archives."
    },
    {
      type: "negative",
      level: "Nuance 1: Fallacy Refuted",
      simpleTakeaway: "Safety concerns are outdated because origin countries now possess world-class museum facilities.",
      collocation: "conservation parity",
      title: "Refuting the 'Paternalistic Protection' Fallacy",
      desc:
        "Western institutions often cite historical safety concerns, but this paternalistic defense is rendered obsolete by modern origin-nation investments.",
      example:
        "Nigeria's planned Edo Museum of West African Art and Greece's Acropolis Museum provide preservation standards equal to or exceeding traditional Western vaults."
    },
    {
      type: "negative",
      level: "Nuance 2: Diplomatic Solution",
      simpleTakeaway: "Repatriation doesn't stop global exhibition; origin nations can arrange reciprocal rotating loans.",
      collocation: "bilateral cultural treaties",
      title: "Diplomatic Feasibility: Bilateral Loan Treaties over Isolation",
      desc:
        "Repatriation does not necessitate global cultural isolation; once legal ownership is restored to origin countries, reciprocal loan agreements can still facilitate global exhibition.",
      example:
        "Italy regularly loans repatriated Roman artifacts to global museums on temporary rotating schedules while retaining sovereign title."
    },
    {
      type: "negative",
      level: "Nuance 3: Ethical Custodianship",
      simpleTakeaway: "Universal museums cannot claim to be global educational centers while holding onto unreturned wartime plunder.",
      collocation: "ethical custodianship",
      title: "The Universal Museum Fallacy vs. Ethical Custodianship",
      desc:
        "Encyclopedic museums claim global educational value, yet this principle cannot justify retaining antiquities acquired through colonial force or illicit excavation.",
      example:
        "The British Museum holds over eight million items in storage while source communities are entirely deprived of experiencing their ancestral masterpieces."
    },
    {
      type: "negative",
      level: "Nuance 4: Legal Precedent",
      simpleTakeaway: "Returning state-held stolen antiquities shrinks the black market and deters future illegal looting.",
      collocation: "deterring black-market trade",
      title: "Precedent for Restitution: Deterring Illicit Antiquity Markets",
      desc:
        "Returning unprovenanced artifacts establishes vital international legal accountability, systematically shrinking the black-market demand for looted antiquities.",
      example:
        "Strict repatriation pacts between Italy and US institutions have dramatically curtailed the trade of stolen Etruscan artifacts."
    }
  ],

  /*
   * ================================================================
   * STEP 7: DISAGREE POINTS — WHY ARTIFACTS SHOULD REMAIN IN GLOBAL MUSEUMS
   * ================================================================
   * Levelled points for students:
   * Level 1: Global Exposure & World Education (High Impact)
   * Level 2: Advanced Conservation & War Safety (Strategic Depth)
   * Level 3: Common Heritage of Mankind (Philosophical Depth)
   * Level 4: Preventing Diplomatic Gridlock (Practical Reality)
   * Plus 4 Critical Rebuttals & Evaluation Perspectives
   */
  evaluationArguments: [
    {
      type: "argument",
      level: "Level 1: High Impact (Global Access)",
      simpleTakeaway: "Universal museums allow millions of international citizens from all countries to experience world cultures under one roof.",
      collocation: "universal encyclopedic curation",
      title: "Universal Museums & Maximized Global Cultural Exposure",
      reason:
        "Centralizing world cultural treasures in accessible global hub cities ensures that millions of international visitors can learn about diverse civilizations in a single visit.",
      development:
        "Metropolitan museums like the British Museum, the Louvre, and the Metropolitan Museum of Art offer free or low-cost admission to millions of visitors who could never afford to travel to dozens of individual origin nations. This fosters international empathy, cross-cultural literacy, and mutual respect among global citizens.",
      example:
        "Over six million visitors of all nationalities view the Rosetta Stone and Parthenon sculptures annually in London, creating worldwide appreciation for Egyptian and Greek heritage on a scale unattainable in local regional museums."
    },
    {
      type: "argument",
      level: "Level 1: High Impact (Preservation)",
      simpleTakeaway: "Leading international institutions have cutting-edge conservation technology and protect fragile relics from regional conflicts.",
      collocation: "climate-controlled preservation",
      title: "Advanced Conservation Infrastructure & Geopolitical Safety",
      reason:
        "Major international museums possess multi-million-dollar conservation facilities and political stability that protect delicate artifacts from decay, warfare, or political unrest.",
      development:
        "Ancient relics are extraordinarily delicate and prone to irreversible environmental decay. Prominent world museums employ computerized climate-controlled display cases, advanced laser cleaning, and 24/7 security. Distributing cultural artifacts across secure international institutions prevents catastrophic destruction during civil wars, regime changes, or economic crises.",
      example:
        "Treasures preserved in foreign museums survived intact, whereas ancient historical artifacts housed in Mosul, Palmyra, and Baghdad were tragically looted or demolished during regional geopolitical instability."
    },
    {
      type: "argument",
      level: "Level 2: Strategic Depth (Shared Humanity)",
      simpleTakeaway: "Ancient civilizations existed long before modern borders; their creations belong to the collective human family, not one modern government.",
      collocation: "common heritage of mankind",
      title: "Universal Human Heritage Transcending Modern Nation-States",
      reason:
        "The achievements of ancient civilizations belong to the shared legacy of humanity rather than the exclusive property of any modern political entity.",
      development:
        "Modern nation-states are recent political constructs that did not exist when these ancient objects were sculpted millennia ago. Great civilizations such as ancient Mesopotamia, Greece, and Egypt laid the philosophical, scientific, and artistic foundations of our shared world. Restricting artifacts strictly within modern political borders reduces universal human milestones into narrow nationalistic assets.",
      example:
        "Classical Greco-Roman and ancient Egyptian civilizations shaped global philosophy, medicine, and architecture; viewing their relics as universal human milestones reinforces our common global heritage."
    },
    {
      type: "argument",
      level: "Level 2: Strategic Depth (Practicality & Law)",
      simpleTakeaway: "Unconditional repatriation would spark endless legal border disputes over extinct empires and empty global cultural hubs.",
      collocation: "diplomatic impasse",
      title: "Avoiding Diplomatic Chaos & Arbitrary Ownership Disputes",
      reason:
        "Mandating the blanket return of all foreign objects would ignite intractable international legal disputes and dismantle global museum cooperation.",
      development:
        "Many ancient empires (e.g. Ottoman, Roman, Byzantine, Mughal) spanned dozens of modern countries with competing historical claims. Determining which modern country has the 'true' legal right to a 2,000-year-old relic is legally arbitrary and politically contentious. Furthermore, emptying encyclopedic collections would terminate international exhibitions, scholarly loans, and global cultural education.",
      example:
        "Attempting to determine whether an ancient Roman artifact belongs to modern Italy, Tunisia, Turkey, or France would cause diplomatic deadlock rather than cooperative cultural exchange."
    },
    {
      type: "counterpoint",
      level: "Evaluation 1: Loan Treaties",
      simpleTakeaway: "Returning legal ownership doesn't empty museums; origin countries readily offer rotating bilateral loans.",
      collocation: "bilateral rotating loans",
      title: "Bilateral Loan Treaties vs. Permanent Retention",
      reason:
        "The fear of empty museums is overstated because origin countries are eager to sign long-term rotating loan agreements once their legal ownership is formally recognized.",
      development:
        "Restoring sovereign title transforms contentious colonial possession into voluntary cultural diplomacy. Origin nations can loan duplicates and rotating collections to global capitals while keeping core spiritual icons in their homeland.",
      example:
        "Italy's bilateral agreements with American museums show that repatriating looted artifacts actually strengthens cultural diplomacy and rotating loan exhibitions."
    },
    {
      type: "counterpoint",
      level: "Evaluation 2: Conservation Parity",
      simpleTakeaway: "Origin nations now build facilities that match or surpass Western conservation standards.",
      collocation: "world-class domestic infrastructure",
      title: "Modern Conservation Standards in Origin Nations",
      reason:
        "The assertion that developing nations cannot safeguard delicate historical artifacts is refuted by modern world-class conservation facilities.",
      development:
        "Origin countries possess computerized humidity control, laser restoration laboratories, and specialized curatorial staff matching European standards.",
      example:
        "The Grand Egyptian Museum in Cairo and the Acropolis Museum in Athens feature preservation technology equal to or surpassing traditional Western facilities."
    },
    {
      type: "counterpoint",
      level: "Evaluation 3: Digital Replicas",
      simpleTakeaway: "3D virtual scans and exact replicas can educate global visitors while original relics return home.",
      collocation: "high-fidelity 3D facsimiles",
      title: "High-Resolution Digital Replicas for Universal Education",
      reason:
        "Modern 3D scanning and holographic technologies enable global museums to fulfill their educational missions without keeping original sacred relics.",
      development:
        "Ultra-precise facsimiles and interactive digital galleries can bring foreign cultures to life for students in Western hubs while the original, spiritually potent artifacts return to source communities.",
      example:
        "Major global institutions increasingly use full-scale 3D scans and laser facsimiles of ancient tomb paintings for public exhibition and tactile study."
    },
    {
      type: "counterpoint",
      level: "Evaluation 4: Moral Principle",
      simpleTakeaway: "Educational utility cannot justify keeping property that was stolen through wartime violence.",
      collocation: "unconditional restitution of looted art",
      title: "The Invalidation of Wartime Plunder by Educational Utility",
      reason:
        "No matter how educational a museum display is, international ethics dictate that property acquired through violent military conquest must be returned.",
      development:
        "Just as modern international law strictly mandates the restitution of artworks confiscated during World War II, colonial-era loot should not be exempt from restitution under the guise of public education.",
      example:
        "International law courts consistently rule that stolen cultural property must be returned to rightful heirs regardless of current curation quality."
    }
  ],

  facultyAngles: [
    {
      title: "The 1970 UNESCO Convention & Retroactive Justice",
      development:
        "Examine how the 1970 UNESCO Convention on the Means of Prohibiting and Preventing the Illicit Import, Export and Transfer of Cultural Property established modern norms, and debate whether international treaties should retroactively enforce the return of pre-1970 colonial loot."
    },
    {
      title: "Digital Repatriation vs. Physical Restitution",
      development:
        "Critique whether ultra-high-definition 3D scans and laser-replicated facsimiles can fulfill Western museums' educational missions while returning the original sacred physical artifacts to their native lands."
    },
    {
      title: "The Acropolis Museum Model: Debunking Conservation Excuses",
      development:
        "Analyze how Greece purpose-built the state-of-the-art Acropolis Museum in Athens—featuring advanced seismic dampers and climate-controlled glass galleries—specifically dismantling the British Museum's claim that Athens could not safeguard the Parthenon Sculptures."
    },
    {
      title: "The Ethics of the 'Universal Encyclopedic Museum'",
      development:
        "Deconstruct the imperial philosophy behind institutions like the British Museum, Louvre, and Met, questioning whether claiming to represent 'shared human civilization' justifies hoarding looted treasures of colonized peoples."
    },
    {
      title: "Bilateral Long-Term Loan Treaties as a Diplomatic Bridge",
      development:
        "Explore legal frameworks where sovereign title is formally transferred back to the country of origin, followed by reciprocal long-term loans that guarantee ongoing international public exposure."
    },
    {
      title: "The Illicit Black Market & Modern Antiquity Looting",
      development:
        "Discuss how strict institutional repatriation policies deter ongoing tomb raiding and black-market antiquities smuggling by removing Western commercial demand for illicit artifacts."
    }
  ],

  brainstormCards: [
    {
      question: "Why is an ancient artifact considered far more than decorative art to its native culture?",
      thinkingLens: "Cultural, Spiritual & Religious Identity",
      selfCheck: "Did you consider sacred rituals, ancestral connection, and community identity?",
      idea: "Historical relics embody the living soul, spiritual traditions, and national pride of their people; their absence alienates native populations from their historical roots."
    },
    {
      question: "Under what historical circumstances were the vast majority of contested museum pieces taken?",
      thinkingLens: "Colonial Subjugation & Military Plunder",
      selfCheck: "Did you examine imperial power imbalances, lootings, and unequal treaties?",
      idea: "Most items were seized through military invasion, punitive raids, or colonial coercion, meaning retention in foreign institutions perpetuates historical injustice."
    },
    {
      question: "What financial and educational harm do origin countries suffer when their treasures are held abroad?",
      thinkingLens: "Economic Sovereignty & Native Academic Access",
      selfCheck: "Did you link museum ticket sales and scholar travel barriers to inequality?",
      idea: "Western museums capture millions in heritage tourism profits, while local students and native scholars are priced out of researching their own history due to foreign travel costs."
    },
    {
      question: "How can origin nations effectively disprove the argument that Western museums offer safer preservation?",
      thinkingLens: "Modern Infrastructure & Bilateral Loan Treaties",
      selfCheck: "Can you cite real-world modern museums in Greece, Egypt, or Nigeria?",
      idea: "Developing and Mediterranean nations now build cutting-edge facilities (e.g. Acropolis Museum, Grand Egyptian Museum) that rival Western vaults, while rotating loans ensure global sharing."
    }
  ],

  powerExpressions: [
    {
      expression: "rightful cultural custodianship",
      meaning: "Legitimate and lawful authority over the care and display of a society's heritage.",
      example: "International tribunals increasingly advocate for the rightful cultural custodianship of source nations."
    },
    {
      expression: "rectify historical injustices of colonial plunder",
      meaning: "Make moral and material restitution for goods stolen during imperial conquests.",
      example: "Repatriating the bronzes helps rectify historical injustices of colonial plunder in West Africa."
    },
    {
      expression: "living embodiment of ancestral identity",
      meaning: "Physical objects that represent the active, continuing spirit and history of a community.",
      example: "Indigenous totems are not dead relics, but the living embodiment of ancestral identity."
    },
    {
      expression: "monopolize heritage tourism revenues",
      meaning: "Capture all economic profits from cultural tourism to the exclusion of the creators.",
      example: "European museums should not monopolize heritage tourism revenues derived from foreign antiquities."
    },
    {
      expression: "state-of-the-art conservation standards",
      meaning: "Modern technological measures ensuring optimal climate, security, and restoration.",
      example: "Athens demonstrated state-of-the-art conservation standards in its dedicated Acropolis Museum."
    },
    {
      expression: "sever the spiritual link to native traditions",
      meaning: "Break the connection between current generations and their ancestral rites.",
      example: "Exhibiting sacred masks behind glass severs the spiritual link to native traditions."
    }
  ],

  connectorsTier: {
    sTier: [
      "It is undeniable that historical treasures embody the soul of their creators...",
      "Under the moral imperative of redressing colonial subjugation...",
      "Crucially, returning these relics restores economic and academic sovereignty...",
      "By reuniting fragmented artifacts with their native soil..."
    ],
    aTier: [
      "In light of these historical realities",
      "Consequently, origin nations deserve rightful custody",
      "Moreover, from an economic standpoint",
      "While opponents cite preservation concerns, this argument is disproven by modern facilities"
    ],
    bTier: [
      "First and foremost",
      "In addition to this",
      "For instance",
      "Ultimately, in conclusion"
    ]
  }
};